version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: rockdeals_backend/Dockerfile
    volumes:
      - ./rockdeals_backend:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: .
      dockerfile: rockdeals_frontend/Dockerfile
    volumes:
      - ./rockdeals_frontend:/app
    ports:
      - "5174:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

# SQLite used by backend; data will be created inside rockdeals_backend folder on host
